-- EarthPulse 데이터베이스 스키마

-- 지진 데이터 테이블
CREATE TABLE IF NOT EXISTS earthquakes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  occurred_at DATETIME NOT NULL,
  magnitude DECIMAL(3,1) NOT NULL,
  depth_km DECIMAL(8,2),
  lat DECIMAL(10,7) NOT NULL,
  lng DECIMAL(10,7) NOT NULL,
  place VARCHAR(255),
  source_id VARCHAR(100) NOT NULL UNIQUE,
  day DATE GENERATED ALWAYS AS (DATE(occurred_at)) STORED,
  month DATE GENERATED ALWAYS AS (DATE_FORMAT(occurred_at, '%Y-%m-01')) STORED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_occurred_at (occurred_at),
  INDEX idx_magnitude (magnitude),
  INDEX idx_day (day),
  INDEX idx_month (month),
  SPATIAL INDEX idx_location (lat, lng)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE (TO_DAYS(day)) (
  PARTITION p202401 VALUES LESS THAN (TO_DAYS('2024-02-01')),
  PARTITION p202402 VALUES LESS THAN (TO_DAYS('2024-03-01')),
  PARTITION p202403 VALUES LESS THAN (TO_DAYS('2024-04-01')),
  PARTITION p202404 VALUES LESS THAN (TO_DAYS('2024-05-01')),
  PARTITION p202405 VALUES LESS THAN (TO_DAYS('2024-06-01')),
  PARTITION p202406 VALUES LESS THAN (TO_DAYS('2024-07-01')),
  PARTITION p202407 VALUES LESS THAN (TO_DAYS('2024-08-01')),
  PARTITION p202408 VALUES LESS THAN (TO_DAYS('2024-09-01')),
  PARTITION p202409 VALUES LESS THAN (TO_DAYS('2024-10-01')),
  PARTITION p202410 VALUES LESS THAN (TO_DAYS('2024-11-01')),
  PARTITION p202411 VALUES LESS THAN (TO_DAYS('2024-12-01')),
  PARTITION p202412 VALUES LESS THAN (TO_DAYS('2025-01-01')),
  PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- 대기질 데이터 테이블
CREATE TABLE IF NOT EXISTS air_quality (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  measured_at DATETIME NOT NULL,
  lat DECIMAL(10,7) NOT NULL,
  lng DECIMAL(10,7) NOT NULL,
  country VARCHAR(100),
  city VARCHAR(100),
  location VARCHAR(255),
  parameter VARCHAR(20) NOT NULL,
  value DECIMAL(10,2) NOT NULL,
  unit VARCHAR(20) NOT NULL,
  source_id VARCHAR(100) NOT NULL,
  day DATE GENERATED ALWAYS AS (DATE(measured_at)) STORED,
  month DATE GENERATED ALWAYS AS (DATE_FORMAT(measured_at, '%Y-%m-01')) STORED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_source_param_time (source_id, parameter, measured_at),
  INDEX idx_measured_at (measured_at),
  INDEX idx_parameter_measured (parameter, measured_at),
  INDEX idx_country_city_param (country, city, parameter, measured_at),
  INDEX idx_day (day),
  INDEX idx_month (month),
  SPATIAL INDEX idx_location (lat, lng)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE (TO_DAYS(day)) (
  PARTITION p202401 VALUES LESS THAN (TO_DAYS('2024-02-01')),
  PARTITION p202402 VALUES LESS THAN (TO_DAYS('2024-03-01')),
  PARTITION p202403 VALUES LESS THAN (TO_DAYS('2024-04-01')),
  PARTITION p202404 VALUES LESS THAN (TO_DAYS('2024-05-01')),
  PARTITION p202405 VALUES LESS THAN (TO_DAYS('2024-06-01')),
  PARTITION p202406 VALUES LESS THAN (TO_DAYS('2024-07-01')),
  PARTITION p202407 VALUES LESS THAN (TO_DAYS('2024-08-01')),
  PARTITION p202408 VALUES LESS THAN (TO_DAYS('2024-09-01')),
  PARTITION p202409 VALUES LESS THAN (TO_DAYS('2024-10-01')),
  PARTITION p202410 VALUES LESS THAN (TO_DAYS('2024-11-01')),
  PARTITION p202411 VALUES LESS THAN (TO_DAYS('2024-12-01')),
  PARTITION p202412 VALUES LESS THAN (TO_DAYS('2025-01-01')),
  PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- 수집 로그 테이블
CREATE TABLE IF NOT EXISTS ingest_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(20) NOT NULL,
  window_start DATETIME NOT NULL,
  window_end DATETIME NOT NULL,
  fetched INT DEFAULT 0,
  inserted INT DEFAULT 0,
  updated INT DEFAULT 0,
  failed INT DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_source_created (source, created_at),
  INDEX idx_window (window_start, window_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

